title: Golsa Heidari's Homepage
page-top-title: Golsa Heidari
top-section-bg-text: Computer Engineering
home-subtitle: Golsa Heidari
<!-- copyright-text: '&copy; Golsa Heidari 2023-2026. All Rights Reserved.' -->
